import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import 'primereact/resources/themes/saga-blue/theme.css';  // Tema
import 'primereact/resources/primereact.min.css';           // Componentes de PrimeReact
import 'primeicons/primeicons.css';                         // Iconos de PrimeReact

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen flex flex-col items-center justify-center bg-gray-100"} style={{backgroundColor:"#f3f4f6"}}>
      {children}
      </body>
    </html>
  )
}
